# Generated by Django 3.0.6 on 2020-05-21 06:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=65)),
                ('product_price', models.IntegerField()),
                ('product_category', models.CharField(blank=True, choices=[('Electronics', 'electronics'), ('Clothes', 'clothes'), ('Shoes', 'shoes')], default='elec', max_length=15, null=True)),
                ('product_brand', models.CharField(max_length=45)),
                ('product_desc', models.CharField(max_length=255)),
                ('product_specs', tinymce.models.HTMLField(verbose_name='Specs')),
            ],
        ),
    ]
