# Generated by Django 3.0.6 on 2020-05-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_desc',
        ),
        migrations.AddField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(default='static.png', upload_to=''),
            preserve_default=False,
        ),
    ]
