# Generated by Django 3.0.6 on 2020-05-18 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='blogs.blog'),
        ),
    ]
