# Generated by Django 3.0.6 on 2020-05-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200518_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('webd', 'Web Design'), ('travel', 'Travel'), ('food', 'Food'), ('other', 'Other')], default='webd', max_length=10, null=True),
        ),
    ]
